### PR TITLE
Install linux update

### PR DESCRIPTION
**Pull request by ninsbl**
Update instalation instructions for linux and add some missing parts

### CODE REVIEW

**Comment by rldhont** [comment]
On which linux system did you test the install ?

I wonder if it would not be relevant to add the OS on which the apt-get is valid.

Thanks for your contribution.

**Comment by ninsbl** [comment]
I installed Lizmap on Ubuntu Server 14.04 LTS

Indeed, the different distros have different package manager systems / commands. Would be for sure an advantage to - at least - mention that apt-get would have to be replaced with e.g. yum or whatever...
However, other distros may also have apache conf files in other locations ? It is usually best if those who really use RedHat, Fedora, OpenSUSE ... write and maintain the installation documentation. I have too little experience with other Linux distros unfortunately... 

Anyway, people who install Lizmap and configure apache are most likely also able to adapt the installation procedure to their distro...

Might be an option to place the documentation in a sub-page for debian/ubuntu (under linux) to clarify, that installation instruction for other distros need to be written?

**Comment by rldhont** [comment]
Can you add a line upper the apt-get line to specify that this command line is for Ubuntu 14.04 LTS ? Thanks

On new ubuntu or debian distro, the installation has to be done with PHP7 and it's quite different. My point of you is that user on other distro has to provide specific documentation. And for other ubuntu version a new apt-get command line.

**Comment by ninsbl** [comment]
Done. 14.04 is actually quite outdated (I just did not find the time to migrate). So, maybe once documentation for 16.04 is written this can be kept as a comment (for lazy people like me) and documentation focused on the current OS version...

**Comment by ninsbl** [comment]
Maybe I had that installed already when I installed Lizmap. Anyway, php5-xmlrpc has been added now...

**Comment by rldhont** [comment]
Thanks!

**Pull request merged**
