### PR TITLE
Lossless compression of png images with optipng

### PR DESCRIPTION
**Pull request by nboisteault**
I compressed losslessly png images and saved 33 Mb.
I used : `find . -type f -iname '*.png' -print0 | xargs -P 8 -I {} -0 optipng -o5 -quiet -preserve '{}'`, where `-P 8` means to use 8 cores.
If these modifications are ok they could be pushed in branch above.

### CODE REVIEW

**Comment by Gustry** [comment]
I think if it's lossless, let's do it.

I think the best would be to also remove duplicated images in each locales. Pictures shouldn't be in the `en`, `fr` folders but in the parent directory (unless they are really translated).

**Comment by Gustry** [comment]
For next time, we should switch to JPEG instead of PNG : https://projects.3liz.org/lizmap/lizmap-documentation/issues/1

**Comment by nboisteault** [comment]
I will convert png files to progressive jpg so.

**Comment by nboisteault** [comment]
I close this PR as I'll convert png to progressive jpg in another branch.

**Pull request closed without merging**
