### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by pcav**

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @pcav, I'd like to know why do you remove php5-pgsql from install packages ?
@kimaidou can you confirm this package is not needed ?

**Comment by pcav** [comment]
Because AFAIK it is needed for pg editing. As such, is reported below.

**Comment by pcav** [comment]
More generally, several packages are repeated to have to be installed in the two sections server_configuration end linux.
IMHO this generates confusion.

**Comment by rldhont** [comment]
ok thanks

**Pull request merged**
