### PR TITLE
Update advanced_lizmap_config.rst

### PR DESCRIPTION
**Pull request by josemvm**
Fast Searchs - QuickFinder Plugin

Note:
it is necessary to create the link from the Advanced Configuration item to
> .. _fts-searches:

### CODE REVIEW

**Comment by rldhont** [comment]
@josemvm  Can you add, which lizmap web client version is needed for that ?
thanks!

**Comment by josemvm** [comment]
tested on 3.1 and master version

**Comment by rldhont** [comment]
Can you update the doc with this information, thanks.

**Comment by josemvm** [comment]
done!

**Comment by josemvm** [comment]
sorry, the comment (https://github.com/3liz/lizmap-plugin/pull/83) regarding https://github.com/3liz/lizmap-documentation/pull/79/commits/4c8d9e4396a2272be72958cf7e16fa1cb6763ec4 is wrong, it should refer to https://github.com/3liz/lizmap-documentation/pull/82

i can't delete this comment...

**Comment by rldhont** [comment]
can't update it. too late.

**Comment by rldhont** [comment]
You can do a `commit --amend` to change it, if nof tell me

**Pull request closed without merging**
