### PR TITLE
refactoring the documentation

### PR DESCRIPTION
**Pull request by Gustry**
Ticket #126, no more `advanced_lizmap_config.rst` :)

Work in progress. Suggestions welcome.

- [x] add links between chapter (popups, etc)
- [x] add missing anchor

.. _lizmap-simples-themes:
.. _hide-layers:
.. _lizmap-config-edition:
.. _filter-layer-data-by-group: 

and others

### CODE REVIEW

**Comment by Gustry** [comment]
Screenshot_2019-12-20 Publisher guide

First review welcome.

I'm not very happy of the `QGIS configuration` title. Because it has some not QGIS config too (like the project default image). Any idea?

**Comment by pcav** [comment]
Just 'Configuration'?

**Comment by pcav** [comment]
BTW: maybe this could be the time to make more clear the distinction between QGIS Projects (=Projects) and Lizmap Projects (=Repositiores)? Many people find this confusing, especially in some translations.
Cheers.

**Comment by Gustry** [comment]
Can you please create a separate ticket for that?

**Comment by pcav** [comment]
Done, thanks

**Pull request merged**
